#!/usr/local/bin/bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled

# Border
bspc config focused_border_color        "#22292B"
bspc config normal_border_color         "#22292B"
bspc config active_border_color         "#22292B"
